services:
  playwright:
    build: .
    image: playwright-container
    container_name: playwright
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    working_dir: /rpx-xui-e2e-tests
    volumes:
      - .:/rpx-xui-e2e-tests
    entrypoint: ["/bin/bash"]
